name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**/*.rs"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**/*.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Format code
        run: |
          cargo fmt --all

      - name: push changes
        id: push-changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git config --global user.email "23025996+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git config pull.rebase true
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Automated Cargo fmt changes"; \
            git pull origin ${{github.event.pull_request.head.ref}}; \
            git push origin HEAD:${{github.event.pull_request.head.ref}}
          fi

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run tests
        run: cargo test --verbose
